### ISSUE TITLE
support alternate lines for noqa declaration of import order violations

### ISSUE THREAD

**Issue by jvanasco** [PyCQA/flake8#1993]
### describe the request

I have a few programs that utilize upstream packages that emit warnings on initial import (mostly `pkg_resources` deprecations right now).  This causes issues with commandline scripts, because the warnings are sent to STDERR, suggesting a failure.

The only way to suppress these warnings entirely within Python code is to immediately import `warnings` and configure  `warnings.ignore`.  

There are 2 common ways to do this:

1- the initial lines import a `_warnings_disable.py` file that imports and configure ignores/logging.  
2- the initial lines import `warnings` and configure ignores/logging before importing the offending packages.

In the first example, `I100` must be placed on the first import AFTER importing the out-of-place lines.

In the second example, `E402` must be placed on each import after the out-of-place lines.

It would be beneficial if the ignore statements could instead be placed on the out-of-place lines, so they can be removed when the code is updated.  Under the current implementation, stray ignores are likely to remain when the code is maintained and the warnings configuration is removed.

Current behavior:

```
from . import _configure_warnings  # noqa: F401

import datetime  # noqa: I100
```

Requested behavior:

```
from . import _configure_warnings  # noqa: F401, I10X

import datetime
```

I noted `I10X` because a feature like this might be better implemented with a new code.

Thank you for your consideration.

**Comment by asottile** [comment]
flake8 is a framework and does not implement any checks.  I is not a code by any of the default plugins so you'll want to report your problem to whatever place that has that code

an aside though I think the linter is objectively correct to point out your code as bad practice.  I would hate to maintain something that depends on both import side effects and import ordering *intentionally*
