### ISSUE TITLE
flake8 Plugin For Behave (BDD Python style)

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#596]
In GitLab by @bittner on Jun 26, 2017, 06:24

I would need a plugin that makes `flake8` understand and accept the features [behave](https://behave.readthedocs.io/en/latest/api.html#step-functions) provides, so that all I need to do is install a Python package (= the plugin, let's call it `flake8-behave`) and no violations are reported that are special cases related to `behave`. Specifically, these are:

- no need to import the annotations `given`, `when`, `then` ("F821 undefined name")
- it's okay that all step functions in a module are called `step_impl` ("F811 redefinition of unused 'step_impl'")
- ideally, these rules should only be applied to step implementation modules (i.e. Python files picked up by `behave`)

Existing Plugins?
-----------------

I'm not sure whether this is easily configured using [flake8-putty](https://github.com/jayvdb/flake8-putty), or I'm better off writing a dedicated, small plugin for behave.

If the latter is true, which of the existing plugins is a good role model? (To make my job easier!)

See Also
--------

- [flake8 reports F811 redefinition of unused 'step_impl'](https://github.com/behave/behave/issues/574) (behave issue #574 on GitHub)
- [related background reading](https://behave.readthedocs.io/en/latest/search.html?q=step_impl&check_keywords=yes&area=default) (search in behave docs)
- [Writing Plugins for Flake8](https://flake8.readthedocs.io/en/latest/plugin-development/index.html)  (= note to self)

**Comment by asottile** [comment]
In GitLab by @bittner on Jun 26, 2017, 06:25

changed the description

**Comment by asottile** [comment]
In GitLab by @bittner on Jun 26, 2017, 22:14

changed the description

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jun 27, 2017, 09:47

> no need to import the annotations `given`, `when`, `then` ("F821 undefined name")

This could be done with `--builtins` but you'd want to constrain that to the files intended for usage with behave.

> I'm not sure whether this is easily configured using [flake8-putty](https://github.com/jayvdb/flake8-putty)

The maintainer(s) of flake8-putty may or may not have already upgraded it to work on Flake8 3.0+ yet. I don't know. It would seem a decent option if in fact it works.

You may just be better off writing a plugin but that may also not work since Flake8 has no way of allowing plugins to aid in the decision to select or ignore a violation.

**Comment by asottile** [comment]
In GitLab by @bittner on Jun 27, 2017, 13:35

> that may also not work since Flake8 has no way of allowing plugins to aid in the decision to select or ignore a violation.

That is unfortunate! If I [read the docs](http://flake8.pycqa.org/en/latest/plugin-development/registering-plugins.html?highlight=plugin) well I figure this option is definitely missing. Pylint [seems to have](https://pylint.readthedocs.io/en/latest/reference_guide/extensions.html) this possibility, that's how [pylint-django](https://github.com/landscapeio/pylint-django) (and similar plugins) exists.

It would most probably make sense to have this possibility with flake8 plugins, too.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Jul 1, 2017, 05:38

I'd need to do research into how PyLint handles this, only so that the UX isn't different. I'm concerned, for example, about users having several plugins installed that all want to manage the same violation code. Some want to forcibly select it while others want to ignore it. That becomes a hairy mess. Which one(s) win?

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 16, 2020, 14:19

- `--builtins` solves the magic globals
- `per-file-ignores` solves the F811 issues somewhat

going to close this for now since I don't know that there's much more that flake8 could do here, perhaps when designing a new plugin api I'll consider letting plugins play with options though as Ian notes that is a slippery slope :)

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 16, 2020, 14:19

closed
