### ISSUE TITLE
Flake8 failed to load plugin "pycodestyle"

### ISSUE THREAD

**Issue by HadiSDev** [PyCQA/flake8#1780]
### how did you install flake8?

```console
pyproject.toml > 
[tool.poetry.dev-dependencies]
coverage = "*"
click = "*"
flake8 = "*"
ipykernel = "*"
pytest = "*"
pytest-runner = "*"
black = "^22.3.0"
isort = "*"
pre-commit = "*"
flake8-no-implicit-concat = "^0.3.3"

Python 3.9
```

### unmodified output of `flake8 --bug-report`

```json
Cannot run "flake8 --bug-report" Get the error below
```

#### Commands
flake8

#### Output
raise FailedToLoadPlugin(plugin.package, e)
flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "pycodestyle" due to cannot import name 'missing_whitespace_after_keyword' from 'pycodestyle'

#### versions
flake8 6.0.0
pycodestyle 2.10.0

#### python 
3.9.15

#### OS
Ubuntu 22

**Comment by HadiSDev** [comment]
pycodestyle = 2.9.0 works with flake 5.0.4

**Comment by asottile** [comment]
you've forced incompatible versions of the two. in the future please search your error message and read the issue template as you would have gotten there without my help!

**Comment by HadiSDev** [comment]
@asottile I have not forced the version of pycodestyle to go above. On my M1, 2.10.0 works fine with flake8, when I switched over to Ubuntu it stopped working and I found that weird.

I did also check the previous issues with pycodestyle where the solution was to downgrade the version. What I am having trouble understanding is why it is not a bug?

**Comment by asottile** [comment]
the error message is only possible if you've forced incompatible versions. pip would have issued a warning when doing so

**Comment by sigmavirus24** [comment]
> @asottile I have not forced the version of pycodestyle to go above. On my M1, 2.10.0 works fine with flake8, when I switched over to Ubuntu it stopped working and I found that weird.
> 
> I did also check the previous issues with pycodestyle where the solution was to downgrade the version. What I am having trouble understanding is why it is not a bug?
> 

It's not a bug because you're installation is likely not in a good state. There's two ways to encounter this: you or a dependency of yours is forcing incompatible versions; or you have old files (either flake8, pycodestyle, or some other combination thereof) somewhere on your system that Python is telling us are the ones to use. Either way, there is no big, there is a problem outside of flake8
