### ISSUE TITLE
`flake8 --diff` broken: Regression with flake8 3.7.x

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#667]
In GitLab by @glemaitre on Jan 30, 2019, 03:19

Please read this brief portion of documentation before going any further: http://flake8.pycqa.org/en/latest/internal/contributing.html#filing-a-bug

*Please describe how you installed Flake8*

Example:

```
pip install flake8
```

*Please provide the exact, unmodified output of `flake8 --bug-report`*

```
{
  "dependencies": [
    {
      "dependency": "entrypoints",
      "version": "0.3"
    }
  ],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.7.2",
    "system": "Linux"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.5.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.1.0"
    }
  ],
  "version": "3.7.1"
}
```

*Please describe the problem or feature*

We get the following traceback with the new release:

https://circleci.com/gh/scikit-learn/scikit-learn/45353

```
Traceback (most recent call last):
  File "/usr/local/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/flake8/main/cli.py", line 18, in main
    app.run(argv)
  File "/usr/local/lib/python3.6/site-packages/flake8/main/application.py", line 392, in run
    self._run(argv)
  File "/usr/local/lib/python3.6/site-packages/flake8/main/application.py", line 379, in _run
    self.initialize(argv)
  File "/usr/local/lib/python3.6/site-packages/flake8/main/application.py", line 366, in initialize
    self.make_guide()
  File "/usr/local/lib/python3.6/site-packages/flake8/main/application.py", line 272, in make_guide
    self.guide.add_diff_ranges(self.parsed_diff)
  File "/usr/local/lib/python3.6/site-packages/flake8/style_guide.py", line 432, in add_diff_ranges
    for guide in self.style_guides.values():
AttributeError: 'list' object has no attribute 'values'
```

The command triggering the issue is:

```
git diff --unified=0 1f5bcaeb3..839790d66 -- sklearn/compose/_target.py
sklearn/compose/tests/test_target.py | flake8 --diff --show-source
```

It worked with flake < 3.7

It seems that the lines triggering the error are not covered by tests:

https://codecov.io/gl/pycqa/flake8/src/master/src/flake8/style_guide.py#L432...433

Removing the `.values()` is iterating over the `style_guides` list and give the expected result.

**Comment by asottile** [comment]
In GitLab by @glemaitre on Jan 30, 2019, 03:23

changed the description

**Comment by asottile** [comment]
In GitLab by @glemaitre on Jan 30, 2019, 03:29

changed the description

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 30, 2019, 07:38

Sounds correct, would you like to provide a patch? I can help with a test if you'd like

**Comment by asottile** [comment]
In GitLab by @glemaitre on Jan 30, 2019, 07:40

I'll try to make a PR. I will be happy to get help with the test. I am really not familiar with the codebase even if I use flake8 quite a lot (thanks for the tool :))

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 30, 2019, 08:28

changed title from **{-Regression with flake8 3.7.1-}** to **{+`flake8 --diff` broken: Regression with flake8 3.7.x+}**

**Comment by asottile** [comment]
In GitLab by @glemaitre on Jan 30, 2019, 08:48

mentioned in merge request !292

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 30, 2019, 10:09

closed via merge request !292

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 30, 2019, 10:09

mentioned in commit 941b1208193ec26b7958aa8bf3ad4221fc813e91

**Comment by asottile** [comment]
In GitLab by @asottile on Jan 30, 2019, 12:53

This has been released in 3.7.2 -- thanks again for the issue :tada:

**Comment by asottile** [comment]
In GitLab by @glemaitre on Jan 30, 2019, 12:58

Thanks for the quick release.
