### ISSUE TITLE
Failure with async/await syntax in python 3.5

### ISSUE THREAD

**Issue by asottile** [PyCQA/flake8#449]
In GitLab by @bluefalcon on Oct 19, 2015, 24:07

While running flake8 on the py35 branch of [pulsar](https://github.com/quantmind/pulsar) I get the following stack trace
```
lsbardel@vespa~/workspace/pulsar$ pyenv exec flake8
Process Process-3:
Traceback (most recent call last):
  File "/Users/lsbardel/.pyenv/versions/3.5.0/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/Users/lsbardel/.pyenv/versions/3.5.0/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/lsbardel/.pyenv/versions/3.5.0/lib/python3.5/site-packages/flake8/reporter.py", line 74, in process_main
    self._process_main()
  File "/Users/lsbardel/.pyenv/versions/3.5.0/lib/python3.5/site-packages/flake8/reporter.py", line 50, in _process_main
    self.input_file(filename)
  File "/Users/lsbardel/.pyenv/versions/3.5.0/lib/python3.5/site-packages/flake8/engine.py", line 95, in input_file
    return fchecker.check_all(expected=expected, line_offset=line_offset)
  File "/Users/lsbardel/.pyenv/versions/3.5.0/lib/python3.5/site-packages/pep8.py", line 1412, in check_all
    self.check_ast()
  File "/Users/lsbardel/.pyenv/versions/3.5.0/lib/python3.5/site-packages/pep8.py", line 1358, in check_ast
    checker = cls(tree, self.filename)
  File "/Users/lsbardel/.pyenv/versions/3.5.0/lib/python3.5/site-packages/flake8/_pyflakes.py", line 43, in __init__
    withDoctest=self.withDoctest)
  File "/Users/lsbardel/.pyenv/versions/3.5.0/lib/python3.5/site-packages/pyflakes/checker.py", line 294, in __init__
    self.handleChildren(tree)
  File "/Users/lsbardel/.pyenv/versions/3.5.0/lib/python3.5/site-packages/pyflakes/checker.py", line 547, in handleChildren
    self.handleNode(node, tree)
  File "/Users/lsbardel/.pyenv/versions/3.5.0/lib/python3.5/site-packages/pyflakes/checker.py", line 589, in handleNode
    handler(node)
  File "/Users/lsbardel/.pyenv/versions/3.5.0/lib/python3.5/site-packages/pyflakes/checker.py", line 812, in CLASSDEF
    self.handleNode(stmt, node)
  File "/Users/lsbardel/.pyenv/versions/3.5.0/lib/python3.5/site-packages/pyflakes/checker.py", line 588, in handleNode
    handler = self.getNodeHandler(node.__class__)
  File "/Users/lsbardel/.pyenv/versions/3.5.0/lib/python3.5/site-packages/pyflakes/checker.py", line 458, in getNodeHandler
    self._nodeHandlers[node_class] = handler = getattr(self, nodeType)
AttributeError: 'FlakesChecker' object has no attribute 'ASYNCFUNCTIONDEF'
```

Not sure if you already are working on this issue or I'm doing something wrong.

**Comment by asottile** [comment]
In GitLab by @sigmavirus24 on Oct 26, 2015, 08:07

Fixed by Flake8 2.5.0

**Comment by asottile** [comment]
In GitLab by @neumond on Aug 29, 2016, 24:13

Happens on 2.5.0 and 2.5.4. Python 3.5.2. Works well using flake8 3.0.4
