### ISSUE TITLE
AttributeError: module 'pycodestyle' has no attribute 'missing_whitespace_after_import_keyword'

### ISSUE THREAD

**Issue by rkhudov** [PyCQA/flake8#1636]
### how did you install flake8?

```console
flake8-bugbear==21.4.3
flake8-builtins==1.5.3
flake8-commas==2.0.0
flake8-comprehensions==3.5.0
flake8-docstrings==1.6.0
flake8-eradicate==1.1.0
flake8-mutable==1.2.0
flake8-per-file-ignores==0.8.1
flake8-print==4.0.0
flake8-quotes==3.2.0
flake8==3.9.2
```

### unmodified output of `flake8 --bug-report`

```json
AttributeError: module 'pycodestyle' has no attribute 'missing_whitespace_after_import_keyword'
```

#### what I expected to happen

No errors thrown while running flake8.

#### commands ran

```console
$ flake8 src
...
```

**Comment by asottile** [comment]
search the tracker for duplicates (and read the template)

**Comment by asottile** [comment]
(notably you or your packager is forcing incompatible versions)

**Comment by tiltX** [comment]
I'd just like to add this for anybody who experiences that issue (since this page is the top result when searching for it):

I had used pip3 to install flake8 into my user directory for use with Sublime Text. The error occurred after an upgrade of pycodestyle to the latest required version (>2.9 for flake8==5.0.4).

I did a "pip3 uninstall flake8 pycodestyle". However, there were remnants of flake8 still in .local/lib/python3.6/site-packages/ which I had to clean up. Maybe it wasn't deleted while Sublime Text was still running (who knows). But after reinstalling flake8  and its dependencies in a clean way the error went away.

**Comment by reitzig** [comment]
(Came here via Google.)

In my case, the problem was a stale Jenkins Workspace after a bump of flake from v4 to v6.
Well, I should say the problem is `pip`, but a workaround-fix was to re-create the venv from scratch -- by removing all workspaces resp. recreating the Jenkins Agent.

**Comment by vmonteco** [comment]
> I'd just like to add this for anybody who experiences that issue (since this page is the top result when searching for it):
> 
> I had used pip3 to install flake8 into my user directory for use with Sublime Text. The error occurred after an upgrade of pycodestyle to the latest required version (>2.9 for flake8==5.0.4).
> 
> I did a "pip3 uninstall flake8 pycodestyle". However, there were remnants of flake8 still in .local/lib/python3.6/site-packages/ which I had to clean up. Maybe it wasn't deleted while Sublime Text was still running (who knows). But after reinstalling flake8 and its dependencies in a clean way the error went away.

I also came through my favorite search engine and encountered the same problem.
I had to manually deinstall/reinstall other flake8 related packages (flake8-isort and flake8-bandit) since I encountered similar problem with them.

**Comment by matkoniecz** [comment]
> search the tracker for duplicates (and read the template)

https://github.com/PyCQA/flake8/issues?q=has+no+attribute+%27missing_whitespace_around_operator finds only this

https://github.com/PyCQA/flake8/issues?q=missing_whitespace_around_operator finds https://github.com/PyCQA/flake8/issues/1092 which does not seem related

(I came here from search engine)
